"""upgrade book cover photo to 40 char

Revision ID: 2e40b2832129
Revises: 632589675119
Create Date: 2025-04-29 22:24:13.642296

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e40b2832129"
down_revision: Union[str, None] = "632589675119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "book_cover_photo",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=40),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "book_cover_photo",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
