"""make cover photo nullable for test

Revision ID: c82d0fad36b8
Revises: 2e40b2832129
Create Date: 2025-04-29 22:44:38.985142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c82d0fad36b8"
down_revision: Union[str, None] = "2e40b2832129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "book_cover_photo",
        existing_type=sa.VARCHAR(length=40),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "book_cover_photo",
        existing_type=sa.VARCHAR(length=40),
        nullable=False,
    )
    # ### end Alembic commands ###
