"""give lowest price back to bookstats

Revision ID: c9310bfaaa6f
Revises: af66cea49985
Create Date: 2025-04-25 10:17:04.017310

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9310bfaaa6f"
down_revision: Union[str, None] = "af66cea49985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_stats", sa.Column("lowest_price", sa.Float(), nullable=False))
    op.alter_column(
        "book_stats",
        "avg_rating",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "book_stats",
        "review_count",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_column("book_stats", "ratings_sum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_stats",
        sa.Column("ratings_sum", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "book_stats",
        "review_count",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "book_stats",
        "avg_rating",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=5, scale=2),
        existing_nullable=False,
    )
    op.drop_column("book_stats", "lowest_price")
    # ### end Alembic commands ###
