"""give total star and avg rating

Revision ID: cfdc7f349331
Revises: c9310bfaaa6f
Create Date: 2025-04-25 10:29:32.955526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfdc7f349331"
down_revision: Union[str, None] = "c9310bfaaa6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_stats", sa.Column("total_star", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_stats", "total_star")
    # ### end Alembic commands ###
